### ISSUE TITLE
Are custom binary names supported?

### ISSUE THREAD

**Issue by forgemo** [nihaals/clap-complete-command#13]
I changed the binary name in my cargo.toml. It seems like the custom name is not picked up by to be used in the generated completion script. Instead, the default binary name is used, which is not correct.

**Comment by nihaals** [comment]
It uses the command's "bin" name as mentioned in [the docs](https://docs.rs/clap_complete_command/0.5.1/clap_complete_command/enum.Shell.html#impl-Shell) which can be set with [`Command::set_bin_name()`](https://docs.rs/clap/4.3.21/clap/struct.Command.html#method.set_bin_name).
