### ISSUE TITLE
Consider adding Apache-2.0 license

### ISSUE THREAD

**Issue by Piturnah** [nihaals/clap-complete-command#7]
For this library I would consider -- particularly while there are no other contributors whose code is licensed exclusively under MIT -- dual licensing MIT / Apache-2.0.

The primary reason being that most crates in the Rust ecosystem are licensed this way, or licensed solely under Apache-2.0, and as such this change would improve interoperability. 

There are other good reasons, e.g.:

1. The Apache-2.0 license has protections from patent trolls and an explicit contribution licensing clause.
2. The MIT license (arguably) requires binaries to reproduce countless copies of the same license boilerplate for every MIT library in use.

**Comment by Piturnah** [comment]
Of course, you may have already considered these things, in which case certainly feel free to disregard me :)

**Comment by nihaals** [comment]
[Accurate statistics](https://gist.github.com/passcod/2e1983ce415b32bdf3a0) on the licenses on crates.io show that MIT is actually the most common license, followed by dual licensing MIT/Apache-2.0, although most of the direct dependencies I use personally *are* dual licensed.

One thing I'm unsure about is attribution. I don't want to use license headers and Apache-2.0 doesn't have a way directly in the license to provide the attribution details you would like users to use, and the way mentioned in the license would probably be using a `NOTICE` file, which seems unnecessary.
